// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOw_Bf40atOnkFwDQMBXJ_9KbxVngDCbM',
    appId: '1:689288253470:web:ef738667cfe3ead6889e0f',
    messagingSenderId: '689288253470',
    projectId: 'chairpal-b95f3',
    authDomain: 'chairpal-b95f3.firebaseapp.com',
    storageBucket: 'chairpal-b95f3.firebasestorage.app',
    measurementId: 'G-N0ZC5ZJMBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgC3oVzgWlHegphK4ht_nXfNc_gAjq80U',
    appId: '1:689288253470:android:941badc5a9032a87889e0f',
    messagingSenderId: '689288253470',
    projectId: 'chairpal-b95f3',
    storageBucket: 'chairpal-b95f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCACZcUTrliEx6uFGwLgHTW9JxtNs6QT8',
    appId: '1:689288253470:ios:a6a2d3b84da24690889e0f',
    messagingSenderId: '689288253470',
    projectId: 'chairpal-b95f3',
    storageBucket: 'chairpal-b95f3.firebasestorage.app',
    iosBundleId: 'com.example.chairPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCACZcUTrliEx6uFGwLgHTW9JxtNs6QT8',
    appId: '1:689288253470:ios:a6a2d3b84da24690889e0f',
    messagingSenderId: '689288253470',
    projectId: 'chairpal-b95f3',
    storageBucket: 'chairpal-b95f3.firebasestorage.app',
    iosBundleId: 'com.example.chairPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOw_Bf40atOnkFwDQMBXJ_9KbxVngDCbM',
    appId: '1:689288253470:web:8595d668b331c5b7889e0f',
    messagingSenderId: '689288253470',
    projectId: 'chairpal-b95f3',
    authDomain: 'chairpal-b95f3.firebaseapp.com',
    storageBucket: 'chairpal-b95f3.firebasestorage.app',
    measurementId: 'G-VR60L796VY',
  );
}
